src/Entity/Project.php
<?php
 
namespace App\Entity;
 
use App\Repository\ProjectRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
 
#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;
 
    #[ORM\Column(type: 'string', length: 255)]
    private $name;
 
    #[ORM\Column(type: 'text')]
    private $description;
 
    #[Gedmo\Timestampable(on:"update")]
    #[ORM\Column(type: 'datetime', nullable: true)]
    private $created_at;
 
    #[Gedmo\Timestampable(on:"update")]
    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updated_at;
 
    public function getId(): ?int
    {
        return $this->id;
    }
 
    public function getName(): ?string
    {
        return $this->name;
    }
 
    public function setName(string $name): self
    {
        $this->name = $name;
 
        return $this;
    }
 
    public function getDescription(): ?string
    {
        return $this->description;
    }
 
    public function setDescription(string $description): self
    {
        $this->description = $description;
 
        return $this;
    }
 
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }
 
    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;
 
        return $this;
    }
 
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }
 
    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;
 
        return $this;
    }
}

src/Form/ProjectType.php
<?php
 
namespace App\Form;
 
use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
 
class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
        ;
    }
 
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php
namespace App\Controller;

use App\Entity\Project;
use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


#[Route('/')]
class ProjectController extends AbstractController
{
    #[Route('/', name: 'app_project_index', methods: ['GET'])]
    public function index(Request $request, ProjectRepository $projectRepository): Response
    {
        // Sorting
        $sortColumn = $request->query->get('sort', 'updated_at'); 
        $sortOrder = $request->query->get('order', 'desc'); 

        // Filter
        $filterParams = [
            'name' => $request->query->get('name'),
            'description' => $request->query->get('description')
        ];

        $page = max(1, $request->query->getInt('page', 1));
        $limit = $request->query->getInt('limit', 9);

        // Fetch projects with filters, sorting, and pagination
        $paginator = $projectRepository->findWithFilters($filterParams, [$sortColumn => $sortOrder], $page, $limit);

        return $this->render('project/index.html.twig', [
            'projects' => $paginator,
            'current_page_number' => $page,
            'total_pages' => ceil(count($paginator) / $limit),
            'current_sort_column' => $sortColumn,
            'current_sort_order' => $sortOrder,
            'limit' => $limit,
            'filter_name' => $filterParams['name'] ?? '',
            'filter_description' => $filterParams['description'] ?? ''
        ]);
    }



    #[Route('/new', name: 'create', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($project);
            $entityManager->flush();

            return $this->redirectToRoute('create', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('project/new.html.twig', [
            'project' => $project,
            'form' => $form,
            'current_page' => 'create'
        ]);
    }

    #[Route('/{id<\d+>}', name: 'app_project_show', methods: ['GET'])]
    public function show(Project $project): Response
    {
        return $this->render('project/show.html.twig', [
          'project' => $project,
        ]);
    }

    #[Route('/{id<\d+>}/edit', name: 'app_project_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Project $project, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('project/edit.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    #[Route('/{id<\d+>}', name: 'app_project_delete', methods: ['POST'])]
    public function delete(Request $request, Project $project, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$project->getId(), $request->request->get('_token'))) {
            $entityManager->remove($project);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/project/charts', name: 'project_charts')]
    public function projectCharts(ProjectRepository $projectRepository): Response
    {
        $nameData = $projectRepository->countGroupByName();
        $descriptionData = $projectRepository->countGroupByDescription();

        return $this->render('project/charts.html.twig', [
            'nameData' => $nameData,
            'descriptionData' => $descriptionData,
            'current_page' => 'chart'

        ]);
    }

}

templates/project/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
    </div>
    <button class="btn {{ button_color|default('btn-outline-primary') }}  mt-3">{{ button_label|default('Save Project') }}</button>
{{ form_end(form) }}

templates/project/charts.html.twig
{# templates/project/charts.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Project Charts{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center mb-4">Project Data</h2>
        
        <div class="row">
            <!-- Chart 1: Projects by Name -->
            <div class="col-sm-4 col-md-8 col-lg-4">
                <div class="card">
                    <div class="card-header">
                        Projects by Name
                    </div>
                    <div class="card-body">
                        <canvas id="nameChart"></canvas>
                    </div>
                </div>
            </div>

            <!-- Chart 2: Projects by Description -->
            <div class="col-sm-4 col-md-8 col-lg-4">
                <div class="card">
                    <div class="card-header">
                        Projects by Description
                    </div>
                    <div class="card-body">
                        <canvas id="descriptionChart"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var ctxName = document.getElementById('nameChart').getContext('2d');
            var nameChart = new Chart(ctxName, {
                type: 'pie',
                data: {
                    labels: {{ nameData.labels|json_encode|raw }},
                    datasets: [{
                        data: {{ nameData.data|json_encode|raw }},
                        backgroundColor: ['red', 'blue', 'green', 'yellow', 'purple', 'orange'],
                    }]
                }
            });

            var ctxDescription = document.getElementById('descriptionChart').getContext('2d');
            var descriptionChart = new Chart(ctxDescription, {
                type: 'pie',
                data: {
                    labels: {{ descriptionData.labels|json_encode|raw }},
                    datasets: [{
                        data: {{ descriptionData.data|json_encode|raw }},
                        backgroundColor: ['red', 'blue', 'green', 'yellow', 'purple', 'orange'],
                    }]
                }
            });
        });
    </script>
{% endblock %}

templates/project/edit.html.twig
{% extends 'base.html.twig' %}
  
{% block title %}Edit Project{% endblock %}
  
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Edit LMT</h2>
        <div class="card">
            <div class="card-body">
                {% include 'project/_form.html.twig' with {'button_label': 'Update Project', 'button_color': 'btn-outline-success'}  %}
            </div>
        </div>
    </div>
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Symfony-CRUD-App
{% endblock %}

{% block body %}
	<div class="container">
	<h2 class="text-center my-5">DEMO-->License Project Manager</h2>
		<!-- Filter Form -->
        <form method="get" action="{{ path('app_project_index') }}" class="my-4">
            <div class="row">
                <div class="col">
                    <input type="text" name="name" class="form-control" placeholder="Name" value="{{ app.request.query.get('name') }}">
                </div>
				<div class="col">
                    <input type="text" name="description" class="form-control" placeholder="Description" value="{{ app.request.query.get('description') }}">
                </div>

                <div class="col">
                    <button type="submit" class="btn btn-primary">Filter</button>
                    <a href="{{ path('app_project_index') }}" class="btn btn-secondary">Reset</a>
                </div>
            </div>
        </form>
		<!-- Filter Form End -->
		<div class="card border-primary mb-3">
			<div class="card-body">
				<table class="table border-primary">
					<tr>
						<th><a href="{{ path('app_project_index', {'sort': 'name', 'order': 'asc', 'name': filter_name, 'description': filter_description}) }}">Name ↑</a> | <a href="{{ path('app_project_index', {'sort': 'name', 'order': 'desc', 'name': filter_name, 'description': filter_description}) }}">↓</a></th>
						<th><a href="{{ path('app_project_index', {'sort': 'description', 'order': 'asc', 'name': filter_name, 'description': filter_description}) }}">Description ↑</a> | <a href="{{ path('app_project_index', {'sort': 'description', 'order': 'desc', 'name': filter_name, 'description': filter_description}) }}">↓</a></th>
						<th><a href="{{ path('app_project_index', {'sort': 'created_at', 'order': 'asc', 'name': filter_name, 'description': filter_description}) }}">Date Created ↑</a> | <a href="{{ path('app_project_index', {'sort': 'created_at', 'order': 'desc', 'name': filter_name, 'description': filter_description}) }}">↓</a></th>
						<th><a href="{{ path('app_project_index', {'sort': 'updated_at', 'order': 'asc', 'name': filter_name, 'description': filter_description}) }}">Date Updated ↑</a> | <a href="{{ path('app_project_index', {'sort': 'updated_at', 'order': 'desc', 'name': filter_name, 'description': filter_description}) }}">↓</a></th>
						<th width="240px">Action</th>
					</tr>

					{% for project in projects %}
						<tr>
							<td>{{ project.name }}</td>
							<td>{{ project.description }}</td>
							<td>{{ project.createdAt ? project.createdAt|date('Y-m-d H:i:s') : '' }}</td>
							<td>{{ project.updatedAt ? project.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
							<td>
								<a class="btn btn-primary" href="{{ path('app_project_show', {'id': project.id}) }}">Show</a>
								<a class="btn btn-success" href="{{ path('app_project_edit', {'id': project.id}) }}">Edit</a>
								<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal-{{ project.id }}">Delete</button>

								<!-- Modal for deleting the project -->
								<div class="modal fade" id="deleteModal-{{ project.id }}" tabindex="-1" aria-labelledby="deleteModalLabel-{{ project.id }}" aria-hidden="true">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-header">
												<h5 class="modal-title" id="deleteModalLabel-{{ project.id }}">Confirm Deletion</h5>
												<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
											</div>
											<div class="modal-body">
												Are you sure you want to delete
												{{ project.name }}?
											</div>
											<div class="modal-footer">
												<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
												<form method="post" action="{{ path('app_project_delete', {'id': project.id}) }}" style="display: inline;">
													<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
													<button type="submit" class="btn btn-danger">Delete</button>
												</form>
											</div>
										</div>
									</div>
								</div>
								<!-- End of Modal -->
							</td>
						</tr>
					{% endfor %}
				</table>
			</div>
		</div>

		<!-- Pagination and Row Selection -->
		<nav aria-label="Page navigation" class="mt-4">
			<div class="d-flex justify-content-between align-items-center">
				<!-- Row Selection Dropdown -->
				<div class="dropdown">
					<button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownRowSelection" data-bs-toggle="dropdown" aria-expanded="false">
						Rows: {{ limit }}
					</button>
					<ul class="dropdown-menu" aria-labelledby="dropdownRowSelection">
						<li><a class="dropdown-item" href="{{ path('app_project_index', {'limit': 9, 'page': current_page_number, 'name': filter_name, 'description': filter_description}) }}">9</a></li>
						<li><a class="dropdown-item" href="{{ path('app_project_index', {'limit': 15, 'page': current_page_number, 'name': filter_name, 'description': filter_description}) }}">15</a></li>
						<li><a class="dropdown-item" href="{{ path('app_project_index', {'limit': 25, 'page': current_page_number, 'name': filter_name, 'description': filter_description}) }}">25</a></li>
					</ul>
				</div>

			<!-- Pagination -->
			<ul class="pagination">
				{% set numPagesToShow = 2 %}
				{% set ellipsisShown = false %}

				{% for i in 1..total_pages %}
					{% if i == 1 or i == total_pages or (i >= current_page_number - numPagesToShow and i <= current_page_number + numPagesToShow) %}
						{% set ellipsisShown = false %}
						<li class="page-item {{ i == current_page_number ? 'active' : '' }}">
							<a class="page-link" href="{{ path('app_project_index', {
								'page': i,
								'limit': limit,
								'sort': current_sort_column,
								'order': current_sort_order,
								'name': filter_name,
								'description': filter_description
							}) }}">{{ i }}</a>
						</li>
					{% elseif not ellipsisShown %}
						{% set ellipsisShown = true %}
						<li class="page-item disabled"><span class="page-link">...</span></li>
					{% endif %}
				{% endfor %}
			</ul>
		</div>
	</nav>

	</div>
{% endblock %}

templates/project/new.html.twig
{% extends 'base.html.twig' %}
  
{% block title %}New Project{% endblock %}
  
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Enter LMT</h2>
        <div class="card">
            <div class="card-body">
                 {{ include('project/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}
  
{% block title %}Project{% endblock %}
  
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Show LMT</h2>
        <div class="card">
            <div class="card-body">
                <b class="text-muted">Name:</b>
                <p>{{ project.name }}</p>
                <b class="text-muted">Description:</b>
                <p>{{ project.description }}</p>
                <b class="text-muted">Date Created:</b>
                <p>{{ project.createdAt ? project.createdAt|date('Y-m-d H:i:s') : '' }}</p>
                <b class="text-muted">Date Updated:</b>
                <p>{{ project.updatedAt ? project.updatedAt|date('Y-m-d H:i:s') : '' }}</p>
            </div>
        </div>
    </div>
{% endblock %}